# Generated by Django 3.2.8 on 2021-10-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.CharField(default='', max_length=50),
        ),
    ]
